"""
FastAPI layer serving the cross-domain recommendation engine.

Loads TasteEngine ONCE at startup via the lifespan handler -- see
blend.py's docstring on load time: unpickling the 191MB music CF model
takes ~15s, far too slow to redo on every request. Everything after
startup is fast in-memory lookups.

Run it:
    uv run uvicorn api.main:app --reload
Then open http://127.0.0.1:8000/docs for interactive Swagger docs,
auto-generated by FastAPI -- no separate API documentation to write.
"""
import os
import sys
from contextlib import asynccontextmanager
from typing import List, Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from blend import TasteEngine  # noqa: E402

engine: Optional[TasteEngine] = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global engine
    engine = TasteEngine()
    yield


app = FastAPI(
    title="Taste Engine API",
    description="Cross-domain movie + music recommendations, blending real "
                 "collaborative filtering with a shared content-embedding bridge.",
    lifespan=lifespan,
)


class Item(BaseModel):
    item_id: str
    domain: str
    title: str
    score: Optional[float] = None


class RecommendRequest(BaseModel):
    seed_item_ids: List[str]
    top_k: int = 10


class RecommendResponse(BaseModel):
    movies: List[Item]
    music: List[Item]


def _require_engine() -> TasteEngine:
    if engine is None:
        raise HTTPException(503, "Engine still loading, try again shortly")
    return engine


@app.get("/health")
def health():
    return {"status": "ok", "engine_loaded": engine is not None}


@app.get("/search", response_model=List[Item])
def search(query: str, domain: Optional[str] = None, limit: int = 10):
    """
    Look up items by (partial, case-insensitive) title -- lets a client
    find real item_ids for onboarding without knowing them ahead of time.
    """
    eng = _require_engine()
    domains = [domain] if domain else ("movies", "music")
    results = []
    for d in domains:
        if d not in eng.domain_items:
            raise HTTPException(400, f"Unknown domain: {d}")
        items = eng.domain_items[d]
        matches = items[items["title"].str.contains(query, case=False, na=False, regex=False)]
        for _, row in matches.head(limit).iterrows():
            results.append(Item(item_id=row["item_id"], domain=d, title=row["title"]))
    return results[:limit]


@app.post("/recommend", response_model=RecommendResponse)
def recommend(req: RecommendRequest):
    eng = _require_engine()
    if not req.seed_item_ids:
        raise HTTPException(400, "seed_item_ids cannot be empty")

    try:
        recs = eng.recommend(req.seed_item_ids, top_k=req.top_k)
    except KeyError as e:
        raise HTTPException(404, f"Unknown item_id: {e}")

    def to_items(df, domain):
        return [
            Item(item_id=row.item_id, domain=domain, title=row.title, score=round(float(row.score), 4))
            for row in df.itertuples()
        ]

    return RecommendResponse(
        movies=to_items(recs["movies"], "movies"),
        music=to_items(recs["music"], "music"),
    )
